# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('issue_acked_timestamp', models.DateTimeField(db_column='Issue_Acked_Timestamp')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=511, null=True)),
            ],
            options={
                'db_table': 'acknowledgement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=31)),
                ('enabled', models.IntegerField(db_column='Enabled', default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, db_column='Created_Timestamp')),
                ('z_index', models.IntegerField(db_column='Z_Index')),
                ('parent_id', models.ForeignKey(db_column='Parent_Id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Andon.Concern')),
            ],
            options={
                'db_table': 'concern',
                'ordering': ['z_index'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('issue_raised_timestamp', models.DateTimeField(auto_now_add=True, db_column='Issue_Raised_Timestamp')),
                ('workstation_id', models.IntegerField(db_column='Workstation_Id')),
                ('acked', models.IntegerField(db_column='Acked', default=0)),
                ('concern', models.ForeignKey(db_column='Concern_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='Andon.Concern')),
            ],
            options={
                'db_table': 'issue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotifyRelationship',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('concern', models.ForeignKey(db_column='Concern_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='Andon.Concern')),
            ],
            options={
                'db_table': 'notifyrelationship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SupportPersonnel',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=63)),
                ('uid', models.CharField(db_column='UID', max_length=31, unique=True)),
                ('isActive', models.IntegerField(db_column='IsActive', default=1)),
                ('phoneNo', models.CharField(db_column='PhoneNo', max_length=8, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=63, unique=True)),
            ],
            options={
                'db_table': 'supportpersonnel',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notifyrelationship',
            name='supportPersonnel',
            field=models.ForeignKey(db_column='SupportPersonnel_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='Andon.SupportPersonnel'),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='issue',
            field=models.ForeignKey(db_column='Issue_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='Andon.Issue'),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='supportPersonnel',
            field=models.ForeignKey(db_column='SupportPersonnel_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='Andon.SupportPersonnel'),
        ),
        migrations.AlterUniqueTogether(
            name='notifyrelationship',
            unique_together=set([('supportPersonnel', 'concern')]),
        ),
    ]
